package com.comtop.mynote.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.comtop.mynote.db.NoteVO;

import com.comtop.mynote.db.NoteVODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteVODaoConfig;

    private final NoteVODao noteVODao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteVODaoConfig = daoConfigMap.get(NoteVODao.class).clone();
        noteVODaoConfig.initIdentityScope(type);

        noteVODao = new NoteVODao(noteVODaoConfig, this);

        registerDao(NoteVO.class, noteVODao);
    }
    
    public void clear() {
        noteVODaoConfig.getIdentityScope().clear();
    }

    public NoteVODao getNoteVODao() {
        return noteVODao;
    }

}
