package com.comtop.mynote.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE_VO.
 */
public class NoteVO {

    private Long id;
    private String title;
    private String content;
    private Integer type;
    private java.util.Date createDate;
    private java.util.Date modifyDate;
    private Integer isEdit;

    public NoteVO() {
    }

    public NoteVO(Long id) {
        this.id = id;
    }

    public NoteVO(Long id, String title, String content, Integer type, java.util.Date createDate, java.util.Date modifyDate, Integer isEdit) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.type = type;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.isEdit = isEdit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public java.util.Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    public java.util.Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(java.util.Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public Integer getIsEdit() {
        return isEdit;
    }

    public void setIsEdit(Integer isEdit) {
        this.isEdit = isEdit;
    }

}
